#-------------------------------
# General Site Settings

title: Niximagery | Stories and Images
description: Stories about image making. # this means to ignore newlines until "baseurl:"
url: https://niximagery.com # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog


#-------------------------------
# About Section
author-name:   Nick Hood
author-avatar: NRH-avatar.png


#-------------------------------
# Contact links
facebook:  https://facebook.com/NixImagery
twitter:   https://twitter.com/NixImagery
instagram: https://www.instagram.com/niximagery
github:    https://github.com/NixImagery
flickr:    https://www.flickr.com/photos/mrhood/
# pinterest: https://www.pinterest.com/ # Add your Facebook handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: Niximagery # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.

#-------------------------------
# Pithy photographc quote
pithyquote: 
  - "\"There are always two people in every picture: the photographer and the viewer.\" — Ansel Adams"
  - "\"You don't take a photograph, you make it.\" — Ansel Adams"
  - "\"A photograph is a secret about a secret. The more it tells you the less you know.\" — Diane Arbus"
  - "\"What the Photograph reproduces to infinity has occurred only once\" - Roland Barthes"
  - "\"Make visible, what without you, might perhaps never have been seen.\" ― Robert Bresson"
  - "\"Photography is an immediate reaction, drawing is a meditation.\" ― Henri Cartier-Bresson"
  - "\"Your first 10,000 photographs are your worst.\" ― Henri Cartier-Bresson"
  - "\"Don't shoot what it looks like. Shoot what it feels like.\" ― David Alan Harvey"
  - "\"We learn by shooting to see better without a camera.\" ― Ernst Hass"
  - "\"The thing is, anybody can be happy and cosy. Nothing good happens in the world by being happy and cosy.\" — Alex Honnold"
  - "\"We look at things all the time, but we do not really see them.\" ― Ibarionex Perello"
  - "\"All photographs are memento mori.\" ― Susan Sontag"
  - "\"Photographs are as much an interpretation of the world as paintings and drawings are.\" ― Susan Sontag"
  - "\"The painter constructs, the photographer discloses.\" ― Susan Sontag"
  - "\"There is an aggression implicit in every use of the camera.\" ― Susan Sontag"
  - "\"To photograph someone is a sublimated murder.\" ― Susan Sontag"
  - "\"When Cartier-Bresson goes to China, he shows that there are people in China, and that they are Chinese.\" ― Susan Sontag"
  - "\"With photography, eclecticism has no limits.\" ― Susan Sontag"

#-------------------------------
# Google Analytics
google-analytics: UA-29333042-11 # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: niximagery.us18.list-manage.com/subscribe/post?u=87266cb51fc169a033c1cfe1e&amp;id=a0be9cf040 # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
# permalink: ':title/'
permalink: /:year/:month/:day/:title:output_ext
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 7
paginate_path: "/page/:num"
# paginate_path: "/articles/page:num/"

include:
  - _pages

collections:
  exposures:
    output: true
  cameras:
    output: true

sass:
  sass_dir: _sass
  style: compressed


exclude: 
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - LICENSE
  - README.md
