project:
  type: website
  output-dir: docs
  preview:
    port: 7200
bibliography: ../Dropbox/Bibliographies/NixImagery.bib
csl: ../Dropbox/styles/chicago-author-date-with-ibid.csl
execute:
  freeze: auto  # re-render only when source changes
  
website:
  title: "Niximagery"
  image: images/IMG_9378.png
  page-navigation: true
  site-url: https://niximagery.com
  favicon: img/favicon.ico
  navbar:
    right:
      - text: About
        href: about.qmd
      - text: Stories
        href: Stories
      - text: Moments
        href: Moments
      - icon: github
        href: https://github.com/NixImagery
      - icon: rss
        href: index.xml
  # google-analytics: G-HNH39SN409
  # twitter-card: true
  open-graph: true
  page-footer:
    background: light
    left: "&copy; Nick Hood. Made with [Quarto](https://quarto.org/)."
    right:
      - icon: github
        href: https://github.com/NixImagery
      - text: Mastodon
        href: https://mastodon.scot/@niximagery
      - text: Flickr
        href: https://www.flickr.com/photos/niximagery/
      - text: 500px
        href: https://500px.com/p/niximagery
      - text: LinkedIn
        href: https://linkedin.com/in/Niximagery

format:
  html:
    theme: 
      - sandstone
      - niximagery.scss
    date-format: "Do MMM YYYY"
