site_name: Niximagery
site_description: Stories and images
site_url: https://niximagery.com
site_author: Nick Hood
docs_dir: source
site_dir: docs
repo_url: https://github.com/NixImagery
repo_name: NixImagery
# edit_uri: ""
copyright: Copyright &copy; 1976 - 2022 Nick Hood

theme:
  name: material
  custom_dir: overrides
  favicon: img/favicon.ico
  logo: img/IMG_9378.png
  features:
    - navigation.instant
    - navigation.indexes
    # - navigation.tabs
    # - navigation.sections
    # - toc.integrate

  icon:
    admonition:
      example: fontawesome/brands/flickr # abusing the admonition type

  palette:
    primary: white
    accent: indigo

nav: # There's a bug in the nav handling that makes it case sensitive
  - Home: index.md
  - Stories and images: 
    - stories/index.md
    - 2022: stories/2022/
    - 2021: stories/2021/
    - 2020: stories/2020/
  - Cameras: 
    - cameras/index.md
    - cameras/*
  - Exposure logs: 
    - exposures/index.md
    - 2022: exposures/2022/
    - 2021: exposures/2021/
    - 2020: exposures/2020/
    - 2019: exposures/2019/
  - Index: 'tags.md'

plugins: 
  - search
  - glightbox
  - literate-nav
  - tags:
      tags_file: tags.md
  - git-revision-date-localized
  - rss:
      abstract_chars_count: 160  # -1 for full content
      categories:
        - tags
      comments_path: "#__comments"
      date_from_meta:
        as_creation: "date"
        as_update: false
        datetime_format: "%Y-%m-%d %H:%M"
      enabled: true
      feed_ttl: 1440
      image: https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Feed-icon.svg/128px-Feed-icon.svg.png
      length: 20
      pretty_print: false
      match_path: "Stories/*/.*"
      url_parameters:
        utm_source: "documentation"
        utm_medium: "RSS"
        utm_campaign: "feed-syndication"
  - bibtex:
      bib_file: "/Users/v1nhood/Dropbox/Bibliographies/library.bib"
      csl_file: "/Users/v1nhood/Dropbox/styles/chicago-author-date-16th-edition.csl"
      cite_inline: true
  - print-site # this needs to be the last plugin


markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - footnotes
  - admonition
  - meta
  - toc:
      title: On this page

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/NixImagery
      name: The NixImagery Repository at GitHub
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/niximagery/
      name: NixImagery on Instagram
    - icon: fontawesome/brands/flickr
      link: https://www.flickr.com/photos/niximagery/
      name: NixImagery on Flickr
    - icon: fontawesome/brands/500px
      link: https://500px.com/p/niximagery
      name: NixImagery on 500px

  analytics:
    provider: google
    property: UA-29333042-11

  disqus: 'Niximagery'
