<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.427">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Niximagery – five-films</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../img/favicon.ico" rel="icon">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

<script type="text/javascript">

(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
ga('create', 'UA-29333042-11', 'auto');

ga('send', {
  hitType: 'pageview',
  'anonymizeIp': true,
});
</script>


</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Niximagery</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../Stories" rel="" target="">
 <span class="menu-text">Stories</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../Moments" rel="" target="">
 <span class="menu-text">Moments</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../Cameras" rel="" target="">
 <span class="menu-text">Cameras</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../Exposures" rel="" target="">
 <span class="menu-text">Exposures</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/NixImagery" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/NixImagery" rel="" target=""><i class="bi bi-twitter" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://instagram.com/NixImagery" rel="" target=""><i class="bi bi-instagram" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../index.xml" rel="" target=""><i class="bi bi-rss" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">



<section id="five-films" class="level1">
<h1>Five films</h1>
<p>More random rolls from the COVID era</p>
<p><img src="../../img/Kodak-Ektachrome-E100-20210730_20010914.jpg" class="img-fluid"> <em>February sunset at Patteismuir</em></p>
<p>Continuing the series of films I had lost track of this year, there were another five exposed films kicking about with only partial notes and recall to record them. Again, using my new Digitaliza film holders and a new MacBook Air, the scans were interesting. In this series:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Brand</th>
<th style="text-align: left;">Type</th>
<th style="text-align: left;">ISO</th>
<th style="text-align: left;">Format</th>
<th style="text-align: left;">Exposures</th>
<th style="text-align: left;">Camera</th>
<th style="text-align: left;">Lens</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Kodak</td>
<td style="text-align: left;">Ektachrome E100</td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">120</td>
<td style="text-align: left;">8</td>
<td style="text-align: left;">Fuji GW690ii</td>
<td style="text-align: left;">90mm</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cinestill</td>
<td style="text-align: left;">800 T</td>
<td style="text-align: left;">800</td>
<td style="text-align: left;">35mm</td>
<td style="text-align: left;">36</td>
<td style="text-align: left;">Nikon FM</td>
<td style="text-align: left;">Nikon AI-s 28mm f/2.8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Lomography</td>
<td style="text-align: left;">Metropolis</td>
<td style="text-align: left;">EI 400</td>
<td style="text-align: left;">120</td>
<td style="text-align: left;">12</td>
<td style="text-align: left;">Hasselblad 503CW</td>
<td style="text-align: left;">Zeiss 80mm F2.8 C</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ilford</td>
<td style="text-align: left;">Delta</td>
<td style="text-align: left;">3200</td>
<td style="text-align: left;">35mm</td>
<td style="text-align: left;">36</td>
<td style="text-align: left;">Nikon FM</td>
<td style="text-align: left;">Nikon AI-s 28mm f/2.8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Kodak</td>
<td style="text-align: left;">Portra</td>
<td style="text-align: left;">160</td>
<td style="text-align: left;">35mm</td>
<td style="text-align: left;">36</td>
<td style="text-align: left;">Nikon FM</td>
<td style="text-align: left;">Nikon AI-s 28mm f/2.8</td>
</tr>
</tbody>
</table>
<section id="ektachrome" class="level2">
<h2 class="anchored" data-anchor-id="ektachrome">Ektachrome</h2>
<p>I am becoming a big fan of Kodak’s modern slide film: no big surprise, really, because years ago I favoured Kodachrome and Agfa’s transparency film in my Nikon FM. Here, a few frames in the huge Fuji GW690ii 6 x 9 camera taken around Kilconquhar and St Monans around 9th April. Scanned at 3200 dpi, the digital images are about 80 mega pixels in size, although sharpness doesn’t satisfy the pixel-neurotic: it’s colours that make these images worth making.</p>
<p><img src="../../img/Kodak-Ektachrome-E100-20210730_20292470.jpg" class="img-fluid"> <em>Church at Kilconquhar. Fuji GW690ii, Ektachrome E100</em></p>
<p>The composition here isn’t perfect: it was tempting to crop out the part-of-a-treee on the left of this picture but there is something in me that wants to crop and adjust as little as possible. I can see what I was thinking with the line of the path central to the composition and am pleased that I kept these parallel to the lines of the church tower. There’s always a bit of difference between what you see in the rangefinder window and the image on the film so I consider this a successful image.</p>
<p><img src="../../img/Kodak-Ektachrome-E100-20210730_20370722.jpg" class="img-fluid"> <em>Kilconquhar. Fuji GW690ii, Ektachrome E100</em></p>
<p>I like the colours in this image taken at the loch, facing in the other direction, a few paces from where I captured the church. The complementary sky and grass tones here work for me. What is most impressive with this film stock is that there is almost no post processing required – the header sunset image taken in February at Pattiesmuir shows this, I think, as well as these snaps from Kilconquhar and St.&nbsp;Monans. Sunlight and good skies are a real bonus too.</p>
<p><img src="../../img/Kodak-Ektachrome-E100-20210730_20451049.jpg" class="img-fluid"> <em>St.&nbsp;Monan’s harbour. Fuji GW690ii, Ektachrome E100</em></p>
<p>Taken from the walk down to the famous wonky sea wall at St.&nbsp;Monans, this again might have been cropped on the left if it had been a digital capture. I love the two-weather sky here.</p>
</section>
<section id="cinestill-800t" class="level2">
<h2 class="anchored" data-anchor-id="cinestill-800t">Cinestill 800T</h2>
<p><img src="../../img/Cinestill-800T-20210731_18185960.jpg" class="img-fluid"> <em>Flowers at Dumbarnie Links, Nikon FM, Cinestill 800T</em></p>
<p>Cinestill 800T is a fast popular film stock, with the “T” indicating that it is designed to be used in tungsten light. It’s ideal for shooting urban scenes at night, which was my intention when I bought a few rolls of 135 and 120 at the beginning of 2021. This first roll was exposed in April in a Nikon FM in daylight at Seafield Beach, Dumbarnie Links (frames 16–25) and Elie (frames 26ff). Scanning as before, I processed them in Capture One, severely adjusting white balance and contrast to compensate for the blue shift of the abused film.</p>
<p><img src="../../img/Cinestill-800T-20210731_18112996.jpg" class="img-fluid"> <em>Seafield Beach. Nikon FM, Cinestill 800T</em></p>
<p>This seemed to do the trick, rendering colours realistically with only two slider adjustments off the scanner. I’m learning to not allow the scanner to do anything with the colour of the files it creates. The above image of flowers at Dumbarnie Links illustrates this.</p>
<p>I’m generally pleased with the results if not a little <em>meh</em> about my collection of dead boring images. Cinestill 800T is an exciting film to use for exciting images: punchy urban scenes evocative of some other era or dark filmic concepts. It’s not really meant for landscapes taken on walks, the purpose of which was not photography but clearing heads. I hope my next set of images with this film stock will do it better justice.</p>
<p><img src="../../img/Cinestill-800T-20210731_18550535.jpg" class="img-fluid"> <em>Elie Beach. Nikon FM, Cinestill 800T</em></p>
<p>I do like the rendering of contrast and tone in this film, once adjusted. Below, Lady’s Tower on a sunny day in Fife gives the film a chance to show this to create a nice image that evokes the feeling of the moment it was captured. More than that, I guess, can’t be asked for.</p>
<p><img src="../../img/Cinestill-800T-20210731_19054350.jpg" class="img-fluid"> <em>Lady’s Tower, Elie. Nikon FM, Cinestill 800T</em></p>
</section>
<section id="lomography-metropolis" class="level2">
<h2 class="anchored" data-anchor-id="lomography-metropolis">Lomography Metropolis</h2>
<p><img src="../../img/Lomochrome-Metropolis-EI400-20210801_12592490.jpg" class="img-fluid"> <em>St.&nbsp;Monans, Fife. Hasselblad 503CW, 80mm Zeiss.</em></p>
<p>This film stock was introduced in 2019 as a new film emulsion with extended range, meaning that the sensitivity is stated on the box as ISO 100 – 400 and you take your pick. I exposed this roll at the higher speed to see how it worked there. As with all of the films in this mini-series, I got AG Photographic to develop them for me.</p>
<p><img src="../../img/Lomochrome-Metropolis-EI400-20210801_13364835.jpg" class="img-fluid"> <em>Bass Rock from Crail. Hasselblad 503CW, 80mm Zeiss.</em></p>
<p>I first scanned this roll using 48-bit colour and 6400 dpi settings which produced square image files post-processing of about 180 megapixels. The colours are muted and cool. It took some time to find the correct white balance adjustment in Capture One but I think the image of St Monans church in Fife is a fair rendition of the film’s character. I like that the contrast is strong. You will not see the Hasselblad notches in that image because, as with many of my hand-held photographs, the horizon was a bit squint, as they say around here, so I had to adjust it and crop.</p>
<p><img src="../../img/Lomochrome-Metropolis-EI400-20210801_13364835-1.jpg" class="img-fluid"> <em>Crail, Fife. Hasselblad 503CW, 80mm Zeiss.</em></p>
<p>This was the last useful frame off the roll, as some time later, during a visit to the Hermitage at Dunkeld, I reached for the Hasselblad and forgot there was film in it. Sheer stupidity caused me to open the film back to load a new film without first checking the clever mechanical indicator on the cartridge. I’m going to say that I will not do that again but then again I also say that my next car will be a Maserati.</p>
</section>
<section id="ilford-delta-3200" class="level2">
<h2 class="anchored" data-anchor-id="ilford-delta-3200">Ilford Delta 3200</h2>
<p><img src="../../img/Ilford-Delta-3200-20210801_17251720-1.jpg" class="img-fluid"> <em>St.Monans Harbour. Nikon FM, 28mm f/1.4 AiS</em></p>
<p>As this is a black and white film, I might have developed this myself but as with all of the films in this mini-series, I got AG Photographic to develop it for me. It was scanned at 6400, then 3200 dpi in 24-bit colour (otherwise the scanner screws up the colour profile in the output file). In post-processing, the profile is switched to black and white. The early images were not of good enough resolution to justify 6400 dpi, hence the switch to something lower.</p>
<p><img src="../../img/Ilford-Delta-3200-20210801_16112152.jpg" class="img-fluid"> <em>Edinburgh, from Fife. Nikon FM, 28mm f/1.4 AiS</em></p>
<p>Most of those early frames were quite disappointing, being underexposed and losing detail in the shadows. I’m fairly sure this was a metering issue: I rely on the built-in LED through-the-lens metering when shooting with the Nikon FM and this might be the price of laziness. Some can be recovered, though, and this image shows a sort of moody shoreline to illustrate the point.</p>
<p><img src="../../img/Ilford-Delta-3200-20210801_17025154.jpg" class="img-fluid"> <em>Edinburgh. Nikon FM, 28mm f/1.4 AiS</em></p>
<p>This is the view from my office window on the Holyrood campus. Delta 3200 might suggest a good low-light film but I think it’s more fast than it is good in the dark. It needs light to function properly. The next image also, perhaps, is more suited to the grainy emulsion of Delta 3200.</p>
<p><img src="../../img/Ilford-Delta-3200-20210801_17174590.jpg" class="img-fluid"> <em>The Palace, Rosyth. Nikon FM, 28mm f/1.4 AiS</em></p>
<p>Something more urban in flavour demands not only monochrome but also the character of a grainy film stock like this. I don’t think it handles wide dynamic range the way I had hoped, however. Shooting into the light is probably not the best idea:</p>
<p><img src="../../img/Ilford-Delta-3200-20210801_17251720.jpg" class="img-fluid"> <em>Harbour Bell, St.Monans. Nikon FM, 28mm f/1.4 AiS</em></p>
<p>Delta 3200 can perform well with good light, and yield decent contrasty images if you meter and expose correctly.</p>
</section>
<section id="kodak-portra-160" class="level2">
<h2 class="anchored" data-anchor-id="kodak-portra-160">Kodak Portra 160</h2>
<p><img src="../../img/Kodak-Portra-160-20210808_18071280-2.jpg" class="img-fluid"> <em>Queensferry Crossing from St.&nbsp;Margaret’s Marsh</em></p>
<p>I scanned most of these at 3200 or 4800 dpi in 48-bit colour with the scanner’s colour handling switch off. The first few frames were taken at the Hermitage, near Dunkeld, during a weekend run up to one of our favourite places in May. We needed reflection time and the COVID restrictions were just so that we could do the right thing as we did The Right Thing for us.</p>
<p><img src="../../img/Kodak-Portra-160-20210808_18071280.jpg" class="img-fluid"> <em>Ossian’s Hall. Nikon FM, 28mm f/1.4 AiS</em></p>
<p>The Dunkeld weekend was not in the brightest of sunshine and that tends to wash out the colours in Portra, I think. This is a dark and moody kind of place when it’s overcast, so the image above does portray that. No marks for composition – there’s a better portrait version but that favours the bridge over the hall and I wanted to show that in this post.</p>
<p><img src="../../img/Kodak-Portra-160-20210808_18071280-1.jpg" class="img-fluid"> <em>Queensferry Crossing from St.&nbsp;Margaret’s Marsh</em></p>
<p>There was better light when we walked on the Forth Shore at St.&nbsp;Margaret’s Marsh, between the bridges and the dockyard. Some while later, we were at Loch Lubnaig where the colours of the greenery dominate the images taken with this film.</p>
<p><img src="../../img/Kodak-Portra-160-20210808_18365655.jpg" class="img-fluid"></p>
<p>I’m not such a fan of 160 in anything other than really good daylight. Composition plays a part, too, and these images aren’t my best: the last few frames of the roll were taken at Burntisland.</p>
<p><img src="../../img/Kodak-Portra-160-20210808_18565359.jpg" class="img-fluid"></p>
<!--15 May Strathyre and Lubnaig
FM 8 ff Portra

27 June Fife beach
FM still Portra 160 ff28ff
-->


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/NixImagery">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.instagram.com/niximagery/">
      <i class="bi bi-instagram" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://mastodon.scot/@niximagery">
      <i class="bi bi-mastodon" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/NixImagery">
      <i class="bi bi-twitter" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="https://www.flickr.com/photos/niximagery/">flickr</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="https://500px.com/p/niximagery">500px</a>
  </li>  
</ul>
    </div>
  </div>
</footer>



</body></html>