<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.427">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Niximagery – hasselblad-v</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../img/favicon.ico" rel="icon">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-4JVXWRW1ZT"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-4JVXWRW1ZT', { 'anonymize_ip': true});
</script>


</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Niximagery</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../Stories" rel="" target="">
 <span class="menu-text">Stories</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../Moments" rel="" target="">
 <span class="menu-text">Moments</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../Cameras" rel="" target="">
 <span class="menu-text">Cameras</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../Exposures" rel="" target="">
 <span class="menu-text">Exposures</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/NixImagery" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/NixImagery" rel="" target=""><i class="bi bi-twitter" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://instagram.com/NixImagery" rel="" target=""><i class="bi bi-instagram" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../index.xml" rel="" target=""><i class="bi bi-rss" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">



<section id="hasselblad-v" class="level1">
<h1>Hasselblad V</h1>
<p><img src="../img/s-l1600.jpg" class="img-fluid"> Image copyright © 2020 <a href="https://www.ebay.co.uk/usr/cambrianphoto">Cambrian Photo, Colwyn Bay</a></p>
<p>I bit the bullet on my first Hasselblad on Boxing Day 2020. Experts will immediately notice that it’s a bit of a <em>Frankenblad</em>, with an incongruous silver 1960’s lens on a millennial 503CW body and magazine. There are fans of the older silver lenses, so perhaps it’s not so monstrous a combination. Optically, the older lenses <a href="https://kenrockwell.com/hasselblad/80mm-f28-c.htm">aren’t any different</a> to the newer ones, and the multi-coating of the <strong>T*</strong> lenses was more about marketing than optical performance, according to <a href="https://kenrockwell.com/hasselblad/80mm-f28-c.htm">Ken Rockwell</a>. What I have discovered is that the previous owner knew his Hasselblads and that this is a very good combination indeed.</p>
<section id="introduction-and-the-cost-of-hasselblads" class="level2">
<h2 class="anchored" data-anchor-id="introduction-and-the-cost-of-hasselblads">Introduction and the cost of Hasselblads</h2>
<p>My wife and I <a href="../Cameras/fuji-gw690ii.html">met a guy</a> one frosty morning, out in the countryside with a Hasselblad while his other half was at a car boot sale. He had bought the camera but was unable to tell his wife. I am more fortunate, and my wife is not averse to me owning a Hasselblad but we are both educators and not that flush, so a little humility and frugality is in order. She has helped me be smart and not so impulsive, and had me talk her through the due diligence and research I have done since that first GAS<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> attack a year ago. That said, I have had encouragement in my desire to own a Hasselblad camera system:</p>
<blockquote class="twitter-tweet blockquote">
<p lang="en" dir="ltr">
do it ; - )
</p>
— Dr David Mitchell (@DSM888) <a href="https://twitter.com/DSM888/status/1334098543984906247?ref_src=twsrc%5Etfw">December 2, 2020</a>
</blockquote>
<script async="" src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<p>The piece I refer to in that Tweet is David’s <a href="https://www.japancamerahunter.com/2020/11/hasselblad-a-personal-reflection/">personal reflection</a> on the <a href="https://www.japancamerahunter.com">Japan Camera Hunter</a> blog, in which he sketches the history of Hasselblad and his own passion for the brand. In that post, David describes the development of the cameras from the early models with focal plane shutters and Kodak lenses, to the copal shuttered Zeiss glass that has been part of the success of the V-series. It is these cameras, that became known as the <em>V-series</em>, that I’m keen to explore. David makes an important point that resonates with me:</p>
<blockquote class="blockquote">
<p>“Good design is discreet and intuitive – if it feels like it should do something then well designed things often do – it’s Mac vs PC for me…”</p>
</blockquote>
</section>
<section id="the-parts-of-the-system" class="level2">
<h2 class="anchored" data-anchor-id="the-parts-of-the-system">The parts of the system</h2>
<p>There are separate and distinct parts to the V-system that need to work together to make a camera. The <em>lens</em> attaches to and works with the <em>body</em> to capture light. The body is more than just a box to mount things on to: it houses the controls, the mirror (these are single-lens reflex cameras) and provides the framework for the other system components to interface with. The <em>viewfinder</em> is for the operator to compose the scene with, focusing on the <em>screen</em>. The <em>back</em> captures the image on to film or a digital sensor.</p>
</section>
<section id="series-timeline" class="level2">
<h2 class="anchored" data-anchor-id="series-timeline">500 series timeline</h2>
<table class="table">
<colgroup>
<col style="width: 43%">
<col style="width: 21%">
<col style="width: 34%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Production</th>
<th style="text-align: center;">Model</th>
<th style="text-align: left;">Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1957 – 1970</td>
<td style="text-align: center;">500 C</td>
<td style="text-align: left;">Original Compur leaf-shutter</td>
</tr>
<tr class="even">
<td style="text-align: left;">1970 – 1994</td>
<td style="text-align: center;">500 CM</td>
<td style="text-align: left;">User-changeable screen</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1988 – 1994</td>
<td style="text-align: center;">503 CX</td>
<td style="text-align: left;">Built-in TTL flash meter, “Palpas” shutter coating, improved Acute Matte screen</td>
</tr>
<tr class="even">
<td style="text-align: left;">1994 – 1997</td>
<td style="text-align: center;">501 C</td>
<td style="text-align: left;">Complete kit, A12 magazine, 80mm lens</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1997 – 2005</td>
<td style="text-align: center;">501 CM</td>
<td style="text-align: left;">The best Acute Matte D screen, CW winder, better internal coatings</td>
</tr>
<tr class="even">
<td style="text-align: left;">1996 – 2013</td>
<td style="text-align: center;">503 CW</td>
<td style="text-align: left;">Improved mirror system</td>
</tr>
</tbody>
</table>
</section>
<section id="bodies" class="level2">
<h2 class="anchored" data-anchor-id="bodies">Bodies</h2>
<p>The 500 series cameras, including the super-wide angle SWx (which have fixed lenses), all have a shutter speed from 1 second to 1/500 s (hence the series name). A leaf shutter is in the lens. Later 2000/200 series bodies revert to a focal plane shutter which can fire at up to 1/2000 s. Those have proved to be less reliable than leaf shutters.</p>
<p>Whilst many reviewers and vloggers have 500 CMs, and I really don’t care about flash, the newer models with better mirrors, second shutter coatings and a bright screen seem to be more attractive for a first investment. The newer, slightly larger mirrors in the 503CW and 501CM only make a significant difference with long lenses (in the viewfinder, the older ones have more vignetting).</p>
<section id="designations" class="level3">
<h3 class="anchored" data-anchor-id="designations">Designations</h3>
<p>The <strong>C</strong> indicates compur-shutter compatible, and <strong>M</strong> is a <em>modified</em> designation. <strong>CX</strong> and improved <strong>CXi</strong> are TTF/OTF X-sync flash compatible. The SWA super-wide angle bodies are based on the older series one and two cameras (1000 and 1600). On the lenses, F indicates a focal plane shutter with additional letters to indicate compatibility: <strong>FC</strong>, <strong>FCM</strong> and <strong>FCW</strong> are compatible with Compur lenses.</p>
</section>
</section>
<section id="lenses" class="level2">
<h2 class="anchored" data-anchor-id="lenses">Lenses</h2>
<p>There is a lot of detail out there on the range of lenses in the V-system, and again, <a href="https://emulsive.org/reviews/camera-reviews/hasselblad-camera-reviews/the-hasselblad-v-system-master-guide-c-and-c-t-star-lenses">Emulsive</a> is your starting point for this. Pertinent details are that most of the lenses are Zeiss glass, with the <strong>C T*</strong> designation indicating multicoatings. The “standard” V-series lens is the Zeiss Planar C 80mm f/2.8, being the diameter of the 56mm square image at the film, and being close to “normal” vision. Some initial preferences for a lens:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Name</th>
<th style="text-align: right;">f</th>
<th style="text-align: left;">Max</th>
<th style="text-align: left;">Min</th>
<th style="text-align: left;">Usage</th>
<th style="text-align: left;">Filter</th>
<th style="text-align: left;">Shutter</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Distagon</td>
<td style="text-align: right;">50mm</td>
<td style="text-align: left;">f/4</td>
<td style="text-align: left;">f/22</td>
<td style="text-align: left;">Landscape</td>
<td style="text-align: left;">63 mm</td>
<td style="text-align: left;">Compur Synchro</td>
</tr>
<tr class="even">
<td style="text-align: left;">Distagon</td>
<td style="text-align: right;">60mm</td>
<td style="text-align: left;">f/3.5</td>
<td style="text-align: left;">f/22</td>
<td style="text-align: left;">Landscape</td>
<td style="text-align: left;">B60</td>
<td style="text-align: left;">Compur Synchro</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Planar C</td>
<td style="text-align: right;">80mm</td>
<td style="text-align: left;">f/2.8</td>
<td style="text-align: left;">f/22</td>
<td style="text-align: left;">General</td>
<td style="text-align: left;">B60</td>
<td style="text-align: left;">Compur Syncro</td>
</tr>
<tr class="even">
<td style="text-align: left;">Planar CF</td>
<td style="text-align: right;">80mm</td>
<td style="text-align: left;">f/2.8</td>
<td style="text-align: left;">f/22</td>
<td style="text-align: left;">General</td>
<td style="text-align: left;">B50</td>
<td style="text-align: left;">Prontor CF</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Planar</td>
<td style="text-align: right;">100mm</td>
<td style="text-align: left;">f/3.5</td>
<td style="text-align: left;">f/22</td>
<td style="text-align: left;">Tele, high resolution</td>
<td style="text-align: left;">B50</td>
<td style="text-align: left;">Compur Synchro</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sonnar C</td>
<td style="text-align: right;">150mm</td>
<td style="text-align: left;">f/4</td>
<td style="text-align: left;">f/32</td>
<td style="text-align: left;">Portrait</td>
<td style="text-align: left;">B50</td>
<td style="text-align: left;">Compur Synchro</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sonnar C</td>
<td style="text-align: right;">250mm</td>
<td style="text-align: left;">f/5.6</td>
<td style="text-align: left;">f/45</td>
<td style="text-align: left;">Portrait</td>
<td style="text-align: left;">B50</td>
<td style="text-align: left;">Compur Synchro</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tele-Tessar C</td>
<td style="text-align: right;">350mm</td>
<td style="text-align: left;">f/5.6</td>
<td style="text-align: left;">f/45</td>
<td style="text-align: left;">Tele</td>
<td style="text-align: left;">B50</td>
<td style="text-align: left;">Compur Synchro</td>
</tr>
</tbody>
</table>
<p><strong>C/CT*</strong> lenses are earlier, often found in chrome. They have self-timers and an automatic depth of field indicator (two red marks). C lenses can be used on any V system camera that has interchangeable lenses (i.e.&nbsp;all except the SWC). The <strong>T</strong> indicates multicoating. <em>Note that the 80mm kit C lens sold with the 501C camera is in fact a modified CF lens.</em> Most C/CT* lenses take B50 bayonet filters.</p>
<p><strong>CF</strong> lenses are less “pointy” in appearance and have B60 bayonet filters (because the end of the barrel is wider than the C/CT* lenses). The barrel includes hyperfocal distance scales. The <strong>F</strong> indicates that the lens is compatible with focal plane shutter bodies. Prontor CF shutters are more reliable than Compur Synchro.</p>
<p><img src="../img/apollo08_earthrise.jpg" class="img-fluid"> <strong>Earthrise</strong> This is the iconic image taken on Christmas Eve, 1968 by <a href="https://en.wikipedia.org/wiki/Bill_Anders">Bill Anders</a> during the Apollo 8 mission, on a Hasselblad EL/M and Zeiss Sonnar f/5.6 250mm lens. The Command Module Hasselblad electric camera was normally fitted with an 80mm f/2.8 Zeiss Planar lens, but a bayonet-mount 250mm lens could be fitted for long-distance Earth/Moon photos (<a href="https://www.history.nasa.gov/afj/ap16fj/02photoequip.html">NASA</a>). See also <a href="https://www.wexphotovideo.com/blog/features/photographing-the-moon-landing-the-hasselblad-cameras-of-apollo-11/">Wex’s</a> and <a href="https://www.hq.nasa.gov/alsj/a11/a11-hass.html">NASA</a>’s articles on the Apollo 11 cameras.</p>
</section>
<section id="backs" class="level2">
<h2 class="anchored" data-anchor-id="backs">Backs</h2>
<p>Hasselblad have made improvements with each iteration of the film backs: the later type IV backs have a dark slide holder which I imagine will be a very smart thing to have for a system in my hashy hands. If there’s a nice safe place to put the dark slide, then I’m less likely to sit on it or drop it in a river. This Hasselblad is going outdoors. <a href="https://kenrockwell.com/hasselblad/a12.htm">Ken Rockwell</a> has a simple guide: there are four generations of A type film magazines (“backs”). There’s no functional difference between them.</p>
</section>
<section id="acquisition" class="level2">
<h2 class="anchored" data-anchor-id="acquisition">Acquisition</h2>
<p>At best I was looking for a 501 CM or 503 CW with a 42204 screen; an A12 Type IV back; waist-level viewfinder; and <em>preferably</em> a late model 80mm C (CF) Planar lens (although a good early one is OK). Things to watch for:</p>
<ul>
<li>That the body, screen and back are of similar age</li>
<li>Serial numbers of back, roll carrier and dark slide match (last 3 digits)</li>
</ul>
<p>What I settled on was this:</p>
<table class="table">
<thead>
<tr class="header">
<th>Back</th>
<th>Body</th>
<th>Lens</th>
<th>VF</th>
<th>Screen</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A12 IV SS 00</td>
<td>503CW EU 97</td>
<td>80mm F2.8 C 67</td>
<td>WL</td>
<td>Acute Matte</td>
</tr>
</tbody>
</table>
<p>You do have to take your time and do your homework, I am learning. eBay is not usually the right place to buy anything over £100, because it’s full of crims and druggies. There are good sellers there, however, including reputable businesses. <a href="https://www.kenrockwell.com/tech/ebay/index.htm">Ken Rockwell</a>’s guide is right on the money when it comes to evaluating sellers:</p>
<blockquote class="blockquote">
<p>“The seller’s feedback rating is a better predictor of the quality of an item than his description of it.”</p>
</blockquote>
<p>Ken suggests that:</p>
<blockquote class="blockquote">
<p>“Good feedback ratings are 99.8% and above. Bad feedback ratings are 99.6% and below. Don’t even consider buying from anyone with much less of a feedback rating than 99.5%. When I have, I’ve often gotten junk.”</p>
</blockquote>
<p>I’m stoked to own my own Hasselblad camera: 2021 is looking to be a good year already.</p>
</section>
<section id="sources" class="level2">
<h2 class="anchored" data-anchor-id="sources">Sources</h2>
<p>As well as David Mitchell’s piece in Japan Camera Hunter, I am grateful to a number of authors and publishers for sharing useful guides and instruction on the Hasselblad <em>marque</em>, not least of which is the superb <a href="https://emulsive.org/reviews/camera-reviews/hasselblad-camera-reviews/the-hasselblad-v-system-master-guide-overview">Emulsive Hasselblad V-System Master Guide</a> by Emmett Brown<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>. If you’re curious about Hasselblad, you could do worse than just read his articles. Others, in no particular order, include <a href="http://www.photoethnography.com/ClassicCameras/Hasselblad500.html">Photoethnography</a>; <a href="http://www.hasselbladhistorical.eu/">Hasselblad historical</a>; <a href="https://beyondtheaperture.com/2019/12/review-hasselblad-503cw-medium-format-film-camera/">Wesley King</a>’s review of the 503CW; and <a href="https://www.hasselblad.com/inspiration/history/500-series/">Hasselblad.com</a>.</p>
<p>There are lots of other videos and posts that I’ve found since first posting this article, but I really like this one by <a href="https://www.instagram.com/studionextimage/">Sails Chong</a>:</p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/KWJSnTLvOow" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="">
</iframe>
<p>“A collection of shiny smile”, indeed.</p>
</section>
<section id="dating-code" class="level2">
<h2 class="anchored" data-anchor-id="dating-code">Dating code</h2>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;">V</th>
<th style="text-align: center;">H</th>
<th style="text-align: center;">P</th>
<th style="text-align: center;">I</th>
<th style="text-align: center;">C</th>
<th style="text-align: center;">T</th>
<th style="text-align: center;">U</th>
<th style="text-align: center;">R</th>
<th style="text-align: center;">E</th>
<th style="text-align: center;">S</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">0</td>
</tr>
</tbody>
</table>


</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Gear Acquisition Syndrome. Photographers get it. Guitarists get it. Artists get it. You get it.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>No, not <a href="https://en.wikipedia.org/wiki/Emmett_Brown">that one</a>. <a href="https://www.facebook.com/emulsive.overlord">The other one</a>. He says that his site is not his “day job” yet so he tends to be professionally coy, using the epithet, “EM”.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">© Nick Hood. Made with <a href="https://quarto.org/">Quarto</a>.</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/NixImagery">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.instagram.com/niximagery/">
      <i class="bi bi-instagram" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://mastodon.scot/@niximagery">
      <i class="bi bi-mastodon" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/NixImagery">
      <i class="bi bi-twitter" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="https://www.flickr.com/photos/niximagery/">flickr</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="https://500px.com/p/niximagery">500px</a>
  </li>  
</ul>
    </div>
  </div>
</footer>



</body></html>